### ISSUE TITLE
Clarification of relation to RealFaviconGenerator

### ISSUE THREAD

**Issue by neopostmodern** [haydenbleasel/gulp-favicons#16]
I was trying to find a more in-depth documentation of the configuration of the icon (it's currently not quite looking right) and saw that http://realfavicongenerator.net/ now has a gulp-export feature.
To my surprise, it points to [another gulp-package](https://github.com/RealFaviconGenerator/gulp-real-favicon).

So, what is the relationship between two projects? How are they different/the same? Will they use the same options eventually so we can export from the website?

**Comment by haydenbleasel** [comment]
Hey @neopostmodern, good question, I'll probably add this to the README to clear this confusion up:

Favicons originally started locally generating images using ImageMagick for versions 1 through 2. Version 3 was the result of working directly with @phbernard (RealFaviconGenerator) to create a module wrapper for their API. This was good as all the logic, generation and everything was managed by RFG, but the problem was that it usually takes too long. So, version 4 (current) is a complete rewrite using a pure-JavaScript solution but also maintaining an optional RFG integration should you choose to go with them. The current aim of Favicons is to replicate every feature of the RFG API without resorting to a web API. Most of this is done, there's just some bits missing in regards to SVG processing which we're working on now.

A side-effect of this messy process has been the development of modules on both sides and we're not currently sure what we're doing with the other modules, but the general gist is that Favicons encompasses local generation as well as interaction with the RFG API faster and cleaner than the official `rfg-api` module. I'll leave this issue open until we actually come up with a solution to this.

**Comment by phbernard** [comment]
That's right. `gulp-real-favicon` will eventually use `favicons` instead of `rfg-api`.

As an aside: RFG's configuration is complex... and is not at the same time. Wow :-) Actually, you are not supposed to write it by hand. Instead, visit https://realfavicongenerator.net/, create your favicon as usual, and on the result page, click the "Gulp" tab. Your configuration is right here, ready to be copied to your Gulpfile.

**Comment by neopostmodern** [comment]
Okay, so if the underlying `favicons` is the long-term solution, is there any chance we can use RFG's amazing code generator with `gulp-favicons`? It's a very helpful to see the result visually and then just export.
Or will that be covered by the `gulp-real-favicon` package while it under the hood talks to `favicons`?

**Comment by haydenbleasel** [comment]
@neopostmodern I think the general idea at the moment is to pick a gulp module and run with it, you'll get a very similar result (and we're working towards making them exact duplicates).

Gulp-Favicons:

```
var favicons = require("gulp-favicons");

gulp.task("default", function () {
    gulp.src("logo.png").pipe(favicons({
        appName: "My App",
        appDescription: "This is my application",
        developerName: "Hayden Bleasel",
        developerURL: "http://haydenbleasel.com/",
        background: "#020307",
        path: "favicons/",
        url: "http://haydenbleasel.com/",
        display: "standalone",
        orientation: "portrait",
        version: 1.0,
        logging: false,
        online: false
        html: "index.html"
    })).pipe(gulp.dest("./"));
});
```

Gulp-Real-Favicon:

```
var realFavicon = require ('gulp-real-favicon');
var fs = require('fs');

// File where the favicon markups are stored
var FAVICON_DATA_FILE = 'faviconData.json';

// Generate the icons. This task takes a few seconds to complete. 
// You should run it at least once to create the icons. Then, 
// you should run it whenever RealFaviconGenerator updates its 
// package (see the check-for-favicon-update task below).
gulp.task('generate-favicon', function(done) {
	realFavicon.generateFavicon({
		"api_key": "87d5cd739b05c00416c4a19cd14a8bb5632ea563",
		"master_picture": {
			"type": "url",
			"url": "http://somesite.com/some_pic.png"
		},
		"files_location": {
			"type": "path",
			"path": "/path/to/icons"
		},
		"favicon_design": {
			"desktop_browser": {},
			"ios": {
				"picture_aspect": "background_and_margin",
				"margin": "4",
				"background_color": "#123456",
				"startup_image": {
					"master_picture": {
						"type": "url",
						"url": "http://example.com/pic_for_ios_startup.png"
					},
					"background_color": "#654321"
				}
			},
			"windows": {
				"picture_aspect": "white_silhouette",
				"background_color": "#654321"
			},
			"firefox_app": {
				"picture_aspect": "circle",
				"keep_picture_in_circle": "true",
				"circle_inner_margin": "5",
				"background_color": "#456789",
				"manifest": {
					"app_name": "My sample app",
					"app_description": "Yet another sample application",
					"developer_name": "Philippe Bernard",
					"developer_url": "http://stackoverflow.com/users/499917/philippe-b"
				}
			},
			"android_chrome": {
				"picture_aspect": "shadow",
				"manifest": {
					"name": "My sample app",
					"display": "standalone",
					"orientation": "portrait",
					"start_url": "/homepage.html",
					"existing_manifest": "{\"name\": \"Yet another app\"}"
				},
				"theme_color": "#4972ab"
			},
			"safari_pinned_tab": {
				"picture_aspect": "black_and_white",
				"threshold": 60,
				"theme_color": "#136497",
			},
			"coast": {
				"picture_aspect": "background_and_margin",
				"background_color": "#136497",
				"margin": "12%"
			},
			"open_graph": {
				"picture_aspect": "background_and_margin",
				"background_color": "#136497",
				"margin": "12%",
				"ratio": "1.91:1",
			},
			"yandex_browser": {
				"background_color": "background_color",
				"manifest": {
					"show_title": true,
					"version": "1.0"
				}
			}
		},
		"settings": {
			"compression": "3",
			"scaling_algorithm": "Mitchell",
			"error_on_image_too_small": true
		},
		"versioning": {
			"param_name": "ver",
			"param_value": "15Zd8"
		},
		markupFile: FAVICON_DATA_FILE
	}, function() {
		done();
	});
});

// Inject the favicon markups in your HTML pages. You should run 
// this task whenever you modify a page. You can keep this task 
// as is or refactor your existing HTML pipeline.
gulp.task('inject-favicon-markups', function() {
	gulp.src([ 'TODO: List of the HTML files where to inject favicon markups' ])
		.pipe(realFavicon.injectFaviconMarkups(JSON.parse(fs.readFileSync(FAVICON_DATA_FILE)).favicon.html_code))
		.pipe(gulp.dest('TODO: Path to the directory where to store the HTML files'));
});

// Check for updates on RealFaviconGenerator (think: Apple has just
// released a new Touch icon along with the latest version of iOS).
// Run this task from time to time. Ideally, make it part of your 
// continuous integration system.
gulp.task('check-for-favicon-update', function(done) {
	var currentVersion = JSON.parse(fs.readFileSync(FAVICON_DATA_FILE)).version;
	realFavicon.checkForUpdates(currentVersion, function(err) {
		if (err) {
			throw err;
		}
	});
});
```
